services:
  postgres:
    extends:
      file: ./backend/docker-compose.yaml
      service: postgres
  
  backend:
    extends:
      file: ./backend/docker-compose.yaml
      service: backend
  
  # Add frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_MAPBOX_API_KEY=${VITE_MAPBOX_API_KEY}
      - VITE_API_URL=http://backend:${SERVER_PORT}
    depends_on:
      - backend

volumes:
  postgres_data: 