//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::map::Entity")]
    Map,
    #[sea_orm(has_many = "super::party::Entity")]
    Party,
    #[sea_orm(has_many = "super::user_party::Entity")]
    UserParty,
}

impl Related<super::map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Map.def()
    }
}

impl Related<super::party::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Party.def()
    }
}

impl Related<super::user_party::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserParty.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
